os: linux
dist: xenial
addons:
  firefox: latest
  chrome: stable

branches:
  only:
    - master
    # tags
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

cache:
  directories:
    - wasm/target
    - $HOME/.cargo

language: rust
rust: 1.45.0

before_install:
  # Install Node
  - nvm install --lts 12 && nvm use 12
  # Install Rust components
  - rustup component add rustfmt-preview
  - rustfmt -V
  - rustup component add clippy-preview
  - cargo clippy -V
  # Install WASM toolchain
  - rustup target add wasm32-unknown-unknown
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f

install:
  - npm ci

script:
  # Rust-related checks
  - npm run lint-wasm:fmt
  - npm run lint-wasm:clippy
  - npm run test-wasm -- --chrome
  # Front-end checks (`npm run build` should be the first one, it builds WASM)
  - npm run build-opt
  - npm run lint-web
  - npm test
