dist: trusty
addons:
  firefox: latest
  chrome: stable
branches:
  only:
    - master
    # tags
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

cache:
  directories:
    - node_modules
    - wasm/target
    - $HOME/.cargo

language: rust
rust: nightly-2018-11-13

before_install:
  # Install Node
  - nvm install --lts 10 && nvm use 10
  # Install Rust components
  - rustup component add rustfmt-preview
  - rustfmt -V
  - rustup component add clippy-preview
  - cargo clippy -V
  - rustup target add --toolchain nightly-2018-11-13 wasm32-unknown-unknown
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
install:
  - npm ci

script:
  # Rust-related checks
  - npm run lint-wasm:fmt
  - npm run lint-wasm:check
  - npm run lint-wasm:clippy
  - npm run test-wasm
  # Front-end checks
  - npm run lint-web
  - npm test
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  # `dist` directory is built as a part of `script` tasks, in `npm run build`.
  local_dir: dist
  github_token: $GITHUB_TOKEN
  on:
    branch: master
