[package]
name = "ed25519-quirks"
edition = "2018"
version = "0.1.0"
authors = ["Alex Ostrovski <ostrovski.alex@gmail.com>"]
license = "Apache-2.0"
description = "WASM part of the Ed25519 Quirks web app"
repository = "https://github.com/slowli/ed25519-quirks"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# WASM / Web stuff.
wasm-bindgen = "0.2.50"
wee_alloc = { version = "0.4.5", optional = true }
# Main dependencies.
clear_on_drop = "0.2.3"
num-bigint = "0.2.3"
sha2 = { version = "0.8.0", default-features = false }
rand_core = "0.4.0"

[dependencies.curve25519]
package = "curve25519-dalek"
version = "1.2.3"
default-features = false
features = ["u64_backend"]

[dependencies.ed25519]
package = "ed25519-dalek"
version = "1.0.0-pre.1"
default-features = false
features = ["u64_backend"]

[dev-dependencies]
wasm-bindgen-test = "0.2.50"

[features]
default = ["wee_alloc", "clear_on_drop/no_cc"]

[profile.release]
lto = true
opt-level = "s"
