[package]
name = "ed25519-quirks"
version = "0.1.0"
authors = ["Alex Ostrovski <ostrovski.alex@gmail.com>"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# WASM / Web stuff.
cfg-if = "0.1.2"
wasm-bindgen = "0.2"
wee_alloc = { version = "0.4.2", optional = true }
# Main dependencies.
num-bigint = "0.2.1"
sha2 = { version = "0.8.0", default-features = false }
rand_core = "0.2.2"
curve25519-dalek = { version = "=1.0.0-pre.1", default-features = false, features = ["u64_backend", "nightly"] }
ed25519-dalek = { version = "=1.0.0-pre.0", default-features = false, features = ["u64_backend", "nightly"] }

[dev-dependencies]
wasm-bindgen-test = "0.2"

[profile.release]
lto = true
opt-level = "s"