name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache cargo build
        uses: actions/cache@v3
        with:
          path: wasm/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'

      # `--force` flag is required because of pug@3 conflicting with pug-loader peer dependency.
      # pug@3 works fine in practice.
      - run: npm ci --force

      # Rust-related checks
      - name: Format
        run: npm run lint:wasm:fmt
      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --manifest-path wasm/Cargo.toml --all-targets -- -D warnings
      - run: npm run test:wasm -- --chrome --firefox

      # Front-end checks (`npm run build` should be the first one, it builds WASM)
      - run: npm run build
      - run: npm run lint:js
      - run: npm run test:js
